const CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES';
const UPDATE_ERROR = 'UPDATE_ERROR';
const CHECKING_FOR_UPDATE = 'CHECKING_FOR_UPDATE';
const UPDATE_AVAILABLE = 'UPDATE_AVAILABLE';
const UPDATE_NOT_AVAILABLE = 'UPDATE_NOT_AVAILABLE';
const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
const UPDATE_DOWNLOADED = 'UPDATE_DOWNLOADED';
const QUIT_AND_INSTALL = 'QUIT_AND_INSTALL';

export default {
  CHECK_FOR_UPDATES,
  UPDATE_ERROR,
  CHECKING_FOR_UPDATE,
  UPDATE_AVAILABLE,
  UPDATE_NOT_AVAILABLE,
  UPDATE_PROGRESS,
  UPDATE_DOWNLOADED,
  QUIT_AND_INSTALL,
};
